name: Fysio Helsinki
favicon: null
layout_spectrum: 0.29826
typography_spectrum: 0.16364927333779633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#1f1b1c'
    - '#fb8eae'
    - '#5f5e63'
    - '#72e1f4'
  brandStrength: 0.25
  lightness: 0.14212379488162696
  saturation: 0.0276651200838387
  rhythmicContrast: 0.5472822489682585
purpose: []
